import type { Metadata } from "next";
import "./globals.css";
// Header and Footer are intentionally not rendered in RootLayout here
// to avoid duplicating layout in the app router pages. Imports removed.

// Removed Inter font import and configuration

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
