import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ZendeskWidget from "@/components/ZendeskWidget";
import { StorageCartProvider } from "@/contexts/StorageCartContext";
import StorageCart from "@/components/StorageCart";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="antialiased">
        <StorageCartProvider>
          <ZendeskWidget />
          {/* <Header /> */}
          {children}
          <StorageCart />
          {/* <Footer /> */}
        </StorageCartProvider>
      </body>
    </html>
  );
}
